config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root :to => "schools#index"
  resources :schools do
    collection do
      get :search
    end

    resources :comments
      post :confirm, on: :collection
    end
  resources :comments
  resources :votes
  
  namespace :staff do
    root 'top#index'
    get 'login' => 'sessions#new', as: :login
    post 'session' => 'sessions#create', as: :session
    delete 'session' => 'sessions#destroy'
  end
  get 'contact' => 'contacts#index'
    
  post 'contact/confirm' => 'contacts#confirm'
  post 'contact/thanks' => 'contacts#thanks'
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :school
  has_many :vote
  validates :content, presence: true
  validates :name, presence: true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, :presence => {:message => '名前を入力してください'}
  validates :email, :presence => {:message => 'メールアドレスを入力してください'}
  validates :content, :presence => {:message => 'お問い合わせ内容を記載して下さい'}
end

app/models/school.rb
class School < ApplicationRecord
  has_many :comments, dependent: :destroy
end

app/models/staff_member.rb
class StaffMember < ApplicationRecord
  before_validation do
    self.email_for_index = email.downcase if email
  end

  def password=(raw_password)
    if raw_password.kind_of?(String)
      self.hashed_password = BCrypt::Password.create(raw_password)
    elsif raw_password.nil?
      self.hashed_password = nil
    end
  end

end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :comment
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(comment_params)
      if @comment.save
        flash[:notice] = '投稿に成功しました'
        redirect_back(fallback_location: schools_path)
      else
        flash[:notice] = '投稿に失敗しました'
        redirect_back(fallback_location: schools_path)
      end
  end

  def vote
    @comment = Comment.new(comment_params)
  end

  private
    def comment_params
      params.require(:comment).permit(:school_id, :name, :content)
    end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def index
    @contact = Contact.new
    render :action => 'index'
  end

  def confirm
    @contact = Contact.new(contact_params)
    if @contact.valid?
      render :action => 'confirm'
    else
      render :action => 'index'
    end
  end

  def thanks
    @contact = Contact.new(contact_params)
    ContactMailer.contact_mail(@contact).deliver  #追記
    @contact.save
    flash[:notice] = "お問い合わせ頂き、ありがとうございました。"
    render :action => 'thanks'
  end

  private

    def contact_params
      params.require(:contact).permit(:name,:email,:content)
    end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :set_school, only: [:show, :edit ,:update,:destroy]

  def index
    ranking =Comment.all.group(:school_id).order('count(school_id) desc').limit(5).pluck(:school_id)
    @schools = School.find(ranking)
    # エリア別情報取得
    @kantos = School.where(area: "関東地方")
    @chubus = School.where(area: "中部地方")
    @okinawas = School.where(area: "九州／沖縄地方")
    @hokaidos = School.where(area: "北海道／東北地方")
    @kinkis = School.where(area: "近畿地方")
    # 言語
    @java = School.where(language: "java")
    @ruby = School.where(language: "ruby")
    @php = School.where(language: "php")
    @net = School.where(language: ".net")
    @python = School.where(language: "python")
    # 目的
    @hobby = School.where(purpose: "趣味")
    @employment = School.where(purpose: "就職")
    @business = School.where(purpose: "起業")
    @friend = School.where(purpose: "仲間づくり")
  end

  def show
    @vote = Vote
    @plus = Vote.where('comment_id = ? and plus_or_minus= ?', 1, 1)
    @minus = Vote.where('comment_id = ? and plus_or_minus= ?', 1, -1)
    @comment = @school.comments.build
    @comments = @school.comments.page(params[:page])
    render layout: 'show'
  end

  def search
    @school = School.find_by(id: params[:school_id])
    # binding.pry
    render json: @school
  end

  private
    def set_school
      @school = School.find(params[:id])
    end

end

app/controllers/staff/base.rb
class Staff::Base < ApplicationController
  before_action :authorize
  layout 'staff'

  private
  def current_staff_member
    if session[:staff_member_id]
      @current_staff_member ||=
        StaffMember.find_by_id(session[:staff_member_id])
    end
  end

  helper_method :current_staff_member

  def authorize
    unless current_staff_member
      flash.alert = '職員としてログインしてください。'
      redirect_to :staff_login
    end
  end
end

app/controllers/staff/sessions_controller.rb
class Staff::SessionsController < Staff::Base
  skip_before_action :authorize
  def new
    if current_staff_member
      redirect_to :staff_root
    else
      @form = Staff::LoginForm.new
      render action: 'new'
    end
  end

  def create
    @form = Staff::LoginForm.new(staff_params)
    if @form.email.present?
      staff_member = StaffMember.find_by(email_for_index: @form.email.downcase)
    end

    if Staff::Authenticator.new(staff_member).authenticate(@form.password)
      if staff_member.suspended?
        flash.now.alert = 'アカウントが停止されています。'
        render action: 'new'
      else
        session[:staff_member_id] = staff_member.id
        flash.notice = 'ログインしました。'
        redirect_to :staff_root
      end
    else
      flash.now.alert = 'メールアドレスまたはパスワードが正しくありません。'
      render action: 'new'
    end
  end

  def destroy
    session.delete(:staff_member_id)
    flash.notice = 'ログアウトしました。'
    redirect_to :staff_root
  end

  private

  def staff_params
    params.require(:staff_login_form).permit(:email, :password)
  end
end

app/controllers/staff/top_controller.rb
class Staff::TopController < Staff::Base
  def index
    render action: 'index'
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  def create
    comment_id = params[:comment_id]
    @comment = Comment.find(comment_id)

    #過去にクッキーの設定してない場合、設定
    if cookies[:cookie].blank?
      cookie = Time.now.to_i.to_s + [*1..1000000].sample.to_s
      cookies.encrypted[:cookie] = { :value => cookie, :expires => 30.days.from_now }
    end

    #クッキーを取り出す
    user_cookie = cookies[:cookie]


    #DBにクッキーidがない場合のみ、保存。
    if Vote.find_by(comment_id: comment_id,cookie: user_cookie).blank?

      if params[:is_up] == "true"
        plus_or_minus = 1
      else
        plus_or_minus = -1
      end
        Vote.create(comment_id: comment_id, cookie: user_cookie, plus_or_minus: plus_or_minus)

    else
      puts "すでに投稿済みのため、保存しません"
    end
      
      @vote = Vote
  end
  private
    def vote_params
      params.require(:vote).permit(:comment_id, :cookie, :plus_or_minus)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
  def date_japan(time)
    time.strftime("%Y年/%m月/%d日(#{%w(日 月 火 水 木 金 土)[time.wday]}) %H:%M:%S")
  end

  def comment_date(id, name, day)
    id.to_s + ' ' + name.to_s + ' '+ day.to_s
  end
end

app/helpers/votes_helper.rb
module VotesHelper
  def plus_vote(vote, comment_number)
    vote.where('comment_id = ? and plus_or_minus= ?', comment_number, 1).count
  end

  def minus_vote(vote, comment_number)
    vote.where('comment_id = ? and plus_or_minus= ?', comment_number, -1).count
  end
end

app/views/comments/_comment.html.slim
.panel.panel-default.comments__area_center
  | コメント一覧
  - comments.each_with_index do |comment, count|
    .comments__data
      - if comment.created_at.present?
        - page_num = 500
        - page_pa = params[:page].to_i
        p= comment_date("#{(page_pa * page_num) + (count + 1)}" , comment.name, date_japan(comment.created_at))
      .comments__item
        = comment.content
      .comments__plus_minus.mt-xl
        .progress.comments__progress_center
          .progress-bar.progress__bar_color.progress-bar-success[role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width:#{plus_vote(@vote, comment.id)}%"]
            = "(Good)" + "#{plus_vote(@vote, comment.id)}"
        .progress.comments__progress_center
          .progress-bar.progress__bar_color.progress-bar-warning[role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width:#{minus_vote(@vote, comment.id)}%"]
            = "(Bad)" + "#{minus_vote(@vote, comment.id)}"
        .comments_vote_area
          = link_to votes_path(comment, params: {is_up: true, comment_id: comment.id, comment: comments}), method: :post, remote: true do
            i.fa.fa-smile-o.fa-3x
          = link_to votes_path(comment, params: {is_up: false, comment_id: comment.id}), method: :post, remote: true do
            i.fa.fa-frown-o.fa-3x
        hr

app/views/comments/_form.html.slim
= form_for([@school,comment]) do |f|
  = f.label :名前
  = f.text_field :name, class: 'form-control', :placeholder => "名前を入力"
  = f.label :コメント
  = f.text_area  :content, rows: 10, class: 'form-control', :placeholder => "コメントを書く"
  = f.hidden_field :school_id, :value => @comment.school_id
  = f.submit 'コメントを投稿する', class: 'btn btn-primary btn-block',:data => { :confirm => '本当に投稿しますか?' }

app/views/comments/create.js.slim
| $("#comments_area").html("#{j(render 'comment', { comments: @comment.school.comments })}");
| $(".form-control").val("");

app/views/contacts/confirm.html.slim
.container
  .row 
    .col-md-8.mt-md
      h1.panel-heading.panel__heading.panel__heading_font_size_sm 
        |お問い合わせ内容確認
      .panel-body.bgc-white
        = form_for @contact, :url => contact_thanks_path do |f|
          table.table
            tr
              th 名前
              td
                = f.hidden_field :name
                = @contact.name
            tr
              th メールアドレス
              td
                = f.hidden_field :email
                = @contact.email
            tr
              th お問い合わせ内容
              td
                = f.hidden_field :content
                = simple_format(@contact.content)
          = f.submit '送信', :class => 'btn btn-primary btn-block mb-sm'
        = form_for(@contact, url: contact_path, method: 'get') do |f|
          = f.hidden_field :name
          = f.hidden_field :email
          = f.hidden_field :content
          = f.submit "もどる", name: 'back', class: 'btn btn-primary btn-block'
    = render 'schools/nav'

app/views/contacts/index.html.slim
.container
  .row
    .col-md-8.mt-md
      h1.panel-heading.panel__heading.panel__heading_font_size_sm 
        |お問い合わせ
      .panel-body.bgc-white
        = form_for @contact, :url => contact_confirm_path do |f|
          .form__error_explanation
            - if @contact.errors.any?
              .alert.alert-danger role="alert"
                strong 入力内容にエラーがあります
                ul
                  - @contact.errors.each do |attr, msg|
                    li= msg
          table.table
            tr
              th
                | 名前
                span.text-danger （必須）
              td= f.text_field :name, size: "40"
            tr
              th
                | メールアドレス
                span.text-danger （必須）
              td= f.text_field :email, size: "40"
            tr
              th
                | お問い合わせ内容
                span.text-danger （必須）
              td= f.text_area :content,:size => "40x10"
          = f.submit '確認', class: 'btn btn-primary btn-block'
    = render 'schools/nav'

app/views/contacts/thanks.html.slim
h1 お問い合わせ完了
p 以下の様に承りました。
table
  tr
    th 名前
    td
      = @contact.name
  tr
    th メールアドレス
    td
      = @contact.email
  tr
    th お問い合わせ内容
    td
      = simple_format(@contact.content)

app/views/layouts/_carousel.html.slim
.container
  aside#my-carousel.carousel.slide[data-ride="carousel" data-interval="8000"]
    ol.carousel-indicators
      li.active[data-target="#my-carousel" data-slide-to="0"]
      li[data-target="#my-carousel" data-slide-to="1"]
      li[data-target="#my-carousel" data-slide-to="2"]
    .carousel-inner.mt-md
      .item.active
       = image_tag("school-mos-1.png")
      .item
       = image_tag("school-mos-2.png")
      .item
       = image_tag("school-mos-3.png")
    a.left.carousel-control[href="#my-carousel" data-slide="prev"]
      span.glyphicon.glyphicon-chevron-left
    a.right.carousel-control[href="#my-carousel" data-slide="next"]
      span.glyphicon.glyphicon-chevron-right

app/views/layouts/_footer.html.slim
footer.mt-xl
  .container
    .row
      .col-sm-8.col-md-9
        ul.navbar-nav.list-inline
          li
            = link_to "ホーム", root_path
          li
            = link_to "アンケート", page_path("enquete")
          li
            = link_to "スクールモスについて", page_path("about")
          li
            = link_to "利用規約", page_path("agreement")
          li
            = link_to "お問い合わせ", contact_path
      .col-sm-4.col-md-3
        .copyright
          |  Copyright © School MOS All rights reserved.

app/views/layouts/_header.html.slim
header
  .container
    h1
      = link_to(root_path) do
        = image_tag "school_mos_logo.png",:size => "150x70"
nav.navbar.navbar-default[role="navigation"]
  .container
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only
          | Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      span.navbar-brand.visible-xs
        | メニュー
    .navbar-collapse.collapse
      ul.nav.navbar-nav
        li
          = link_to root_path do
            | ホーム
            br
            span
              | HOME
        li
          = link_to page_path('enquete') do
            | アンケート
            br
            span
              | ENQUETE
        li
          = link_to page_path('about') do
            | スクールモスについて
            br
            span
              | About
        li
          = link_to page_path('agreement') do
            | 利用規約
            br
            span
              | AGREEMENT
        li
          = link_to contact_path do
            | お問い合わせ
            br
            span
              | CONTACT

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SchoolMos</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/carousel' %>

    <%= yield %>
  <!-- flashにメッセージがある時 -->
  <p class="alert"><%= alert %></p>
  <% unless flash.empty? %>
    <script type="text/javascript">
    <% flash.each do |f| %>
      <% type = f[0].to_s.gsub('alert','error').gsub('notice','info') %>
        toastr['<%= type %>']('<%= f[1] %>');
    <% end %>
  </script>
  <% end %> 
    <%= render :partial =>'layouts/footer' %>
  </body>
</html>

app/views/layouts/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SchoolMos</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  <!-- flashにメッセージがある時 -->
  <p class="alert"><%= alert %></p>
  <% unless flash.empty? %>
    <script type="text/javascript">
    <% flash.each do |f| %>
      <% type = f[0].to_s.gsub('alert','error').gsub('notice','info') %>
        toastr['<%= type %>']('<%= f[1] %>');
    <% end %>
  </script>
  <% end %> 
    <%= render :partial =>'layouts/footer' %>
  </body>
</html>

app/views/layouts/staff.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><スクールモス スタッフログイン画面</title> 
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div id="wrapper">
      <%= render 'staff/shared/header' %> 
      <div id="container">
        <%= yield %>
      </div>
    <%= render :partial =>'layouts/footer' %>
    </div>
  </body> 
</html> 

app/views/pages/about.html.slim
.container
  .row
    .col-md-8.mt-md
      h1.panel-heading.panel__heading.panel__heading_font_size_sm スクールモスについて
      .panel-body.bgc-white
        p サイト開始日　2018年1月1日
        h2 サイト名　プログラミングスクール掲示板サイト　スクールモス
        h2 このサイトについて
        div もすではリアルな『ITスクール』についての情報交換の場を
          提供しています。

        h2  掲載内容について
        p
          | 掲載されている記事・画像等に関して何か問題があればお問い合わせからご連絡下さい。
          br
          | 確認後、適切な対処を取らせていただきます。
    = render 'schools/nav'

app/views/pages/enquete.html.slim
.container
  .row
    .col-md-8.mt-md
      h1.panel-heading.panel__heading.panel__heading_font_size_sm アンケート
      .panel-body.bgc-white
        p <script type="text/javascript" src="http://websurvey-charts.com/api/script/chart-factory/"></script>
        <div class="websurvey-chart" data-source='7b20227175657374696f6e223a207b20226964223a2031333838207d2c20226368617274223a207b202274797065223a2031207d207d' data-decode=true></div>
    = render 'schools/nav'

app/views/schools/_aside.html.slim
.container
  aside#my-carousel.carousel.slide[data-ride="carousel" data-interval="8000"]
    ol.carousel-indicators
      li.active[data-target="#my-carousel" data-slide-to="0"]
      li[data-target="#my-carousel" data-slide-to="1"]
      li[data-target="#my-carousel" data-slide-to="2"]
    .carousel-inner
      .item.active
       = image_tag("school-mos-1.png")
      .item
       = image_tag("school-mos-2.png")
      .item
       = image_tag("school-mos-3.png")
    a.left.carousel-control[href="#my-carousel" data-slide="prev"]
      span.glyphicon.glyphicon-chevron-left
    a.right.carousel-control[href="#my-carousel" data-slide="next"]
      span.glyphicon.glyphicon-chevron-right

app/views/schools/_detail.html.slim
table.table.table-striped
  tr
    td
      | 学校名
    td
      = @school.name
  tr
    td
      | URL
    td
      = @school.url
  tr
    td
      | 学費
    td
      = @school.price.to_s + "万円"
  tr
    td
      | 言語
    td
      = @school.language
  tr
    td
      | 住所
    td
      = @school.area.to_s + @school.address.to_s
  tr
    td
      | リモート
    td
      = @school.remote
  tr
    td
      | 目的
    td
      = @school.purpose

app/views/schools/_header.html.slim
header
  h1
    | スクールモス
nav.navbar.navbar-default[role="navigation"]
  .container
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only
          | Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      span.navbar-brand.visible-xs
        | メニュー
    .navbar-collapse.collapse
      ul.nav.navbar-nav
        li
          a[href="index.html" title="ホーム"]
            | ホーム
            br
            span
              | HOME
        li
          a[href="index.html" title="会社概要"]
            | 会社概要
            br
            span
              | COMPANY
        li
          a[href="index.html" title="サービス"]
            | サービス
            br
            span
              | SERVICE
        li
          a[href="index.html" title="採用情報"]
            | 採用情報
            br
            span
              | RECRIT
        li
          a[href="index.html" title="お問い合わせ"]
            | お問い合わせ
            br
            span
              | CONTACT

app/views/schools/_nav.html.slim
.col-md-3.hidden-sm.menu_display_hidden
  .main
    .panel.panel-default
    .panel-heading.panel__heading.panel__heading_font_size_sm
      p
        | サブメニュー
    .panel-body.panel__body
      .sidebar
        .sidebar__thumbnail
        .sidebar__content

app/views/schools/_school.html.slim
.panel-body.panel__body
  .panel__image
    = link_to "/schools/#{school.id}" do
      = image_tag school.school_image_url
  .panel-wrap.panel__wrap
      .panel__ranking
        p
          sapn.rank1
            | #{school_counter + 1}位 
          i.fa.fa-commenting-o 
            | #{school.comments.count}コメント
            span.time
            = time_ago_in_words(school.created_at)
            | 前
      .panel-content
        = link_to "/schools/#{school.id}" do
          = school.name

app/views/schools/show.html.slim
.wrapper
  .container
    .row
      .col-sm-12.col-md-9.bgc_white
        section
          h1
            = @school.name 
          .school_wrap
            .col-sm-12.col-md-12.school__img
              = link_to image_tag(@school.school_image_url), :href => @school.url
            .col-sm-12.col-md-12
              = render partial: 'schools/detail'
              p
                |ここに特色など書いて行くここに特色など書いて行く
                |ここに特色など書いて行くここに特色など書いて行く
                |ここに特色など書いて行くここに特色など書いて行く
                |ここに特色など書いて行くここに特色など書いて行く
                |ここに特色など書いて行くここに特色など書いて行く
          .school__koushiki
            = link_to image_tag("koushiki.png"), :href => @school.url
      = render 'nav'
      .col-sm-12.col-md-9
        section
            .panel.panel-default
              .panel-body.panel__body.panel__panelbody_center
                .school__image
                  = image_tag(@school.school_image_url,:size => "50x50")
                .school__name
                  .school_name_font
                    = @school.name
                    | について語ろう
                  .school__comment
                  i.fa.fa-commenting-o 
                  | コメント
                  = @school.comments.count
                .school__submit
                  = link_to :anchor => 'form' do
                    button.btn.btn-primary.btn-xl type="button" コメントする
        .comments__area#js-comments__area
          = render partial: 'comments/comment', locals: { comments: @comments }
        #form.panel.panel-default.comments__area_center
          = render partial: 'comments/form', locals: { comment: @comment }
        = paginate @comments

app/views/staff/top/index.html.slim
- @title = '職員トップページ'
= @title

app/views/votes/create.js.slim
| $("#js-comments__area").html("#{j(render 'comments/comment', { comments: @comment.school.comments })}");